program = block "." .

block =
    ["const" ident "=" num {"," ident "=" num} ";"]
    | ["var" ident {"," ident} ";"]
    | {"procedure" ident ";" block ";"} statement .

statement =
    ident ":=" expression
    | "call" ident
    | "begin" statement {";" statement } "end"
    | "if" condition "then" statement
    | "while" condition "do" statement .

condition =
    "odd" expression
    | expression ("="|"#"|"<"|"<="|">"|">=") expression .

expression = ["+"|"-"] term {("+"|"-") term} .

term = factor {("*"|"/") factor} .

factor =
    ident
    | number
    | "(" expression ")" .


prog = { VARSYM,    IDENTSYM,  COMMASYM, IDENTSYM,  SEMISYM,  BEGINSYM, IDENTSYM, EQLSYM,
         NUMBERSYM, SEMISYM,   WHILESYM, IDENTSYM,  BEGINSYM, IDENTSYM, EQLSYM,   IDENTSYM,
         PLUSSYM,   NUMBERSYM, SEMISYM,  IDENTSYM,  EQLSYM,   IDENTSYM, TIMESSYM, NUMBERSYM
         SEMISYM,   ENDSYM,    SEMISYM,  ENDSYM,    PERIODSYM } .

