#!/bin/sh

# To be run from the root directory of the project.

cd daic/Declarations/Generated

if ! command -v python3 >/dev/null
then
	python GenNodeTypes.py
	python GenTokTypes.py
else
	python3 GenNodeTypes.py
	python3 GenTokTypes.py
fi

# Compile packcc
cd ../../../Grammar/packcc/src
cc -O0 packcc.c -o ../../peg

# Use packcc to compile grammar to .h and .c
cd ../../
./peg -o DaishoParser Grammar.peg
rm peg

# Combine the .h and .c file generated by the grammar
cat DaishoParser.h DaishoParser.c > DaishoParser
awk '!/#include "DaishoParser.h"/' DaishoParser > DaishoParser.h
rm DaishoParser.c DaishoParser
mv DaishoParser.h ../daic/AST/Generated/
