#!/bin/sh

cd src/Declarations/Generated

if ! command -v python3 >/dev/null
then
	python GenNodeTypes.py
	python GenTokTypes.py
else
	python3 GenNodeTypes.py
	python3 GenTokTypes.py
fi

# Compile packcc
cd ../../../Grammar/packcc/src
cc -O0 packcc.c -o ../../peg

# Use packcc to compile grammar to .h and .c
cd ../../
./peg -o StiltsParser Grammar.peg
rm peg

# Combine the .h and .c file generated by the grammar
cat StiltsParser.h StiltsParser.c > StiltsParser
awk '!/#include "StiltsParser.h"/' StiltsParser > StiltsParser.h
rm StiltsParser.c StiltsParser
pwd
mv StiltsParser.h ../src/AST/Generated/
