#pragma once
#ifndef __STILTS_STDLIB_GENERATEDCONFIG
#define __STILTS_STDLIB_GENERATEDCONFIG

#define __STILTS_HAS_ANSI_COLORS 1
#define __SILTS_HAS_PYTHON 1
#define __STILTS_PYTHON_EXECUTABLE "/usr/bin/python"
#define __STILTS_PYTHON_VERSION "3.9.2"
#define __STILTS_PYTHON_MAJOR_VERSION 3
#define __STILTS_PYTHON_MINOR_VERSION 9
#define __STILTS_PYTHON_SUBMINOR_VERSION 2
#define __STILTS_PAGESIZE 4096
#define __STILTS_IDEAL_NUM_THREADS 8
#define __STILTS_BACKTRACES_SUPPORTED 1

#endif
