/* A packrat parser generated by PackCC 1.5.1 */

#ifndef PCC_INCLUDED_STILTSPARSER_H
#define PCC_INCLUDED_STILTSPARSER_H

#include <apaz-libc.h>
typedef void* NTYPE;
#ifdef __cplusplus
extern "C" {
#endif

typedef struct StiltsParser_context_tag StiltsParser_context_t;

StiltsParser_context_t *StiltsParser_create(void *auxil);
int StiltsParser_parse(StiltsParser_context_t *ctx, NTYPE *ret);
void StiltsParser_destroy(StiltsParser_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_STILTSPARSER_H */
