#pragma once
#ifndef __STILTS_STDLIB_COLOR
#define __STILTS_STDLIB_COLOR

#ifndef __STILTS_ANSI_TERMINAL
#ifdef _WIN32
#define __STILTS_ANSI_TERMINAL 0
#else
#define __STILTS_ANSI_TERMINAL 1
#endif /* _WIN32 */
#endif /* __STILTS_ANSI_TERMINAL */

#if __STILTS_ANSI_TERMINAL
#define __STILTS_COLOR_BLACK   "\x1b[30m"
#define __STILTS_COLOR_RED     "\x1b[31m"
#define __STILTS_COLOR_GREEN   "\x1b[32m"
#define __STILTS_COLOR_YELLOW  "\x1b[33m"
#define __STILTS_COLOR_BLUE    "\x1b[34m"
#define __STILTS_COLOR_MAGENTA "\x1b[35m"
#define __STILTS_COLOR_CYAN    "\x1b[36m"
#define __STILTS_COLOR_RESET   "\x1b[0m"
#else
#define __STILTS_COLOR_BLACK   ""
#define __STILTS_COLOR_RED     ""
#define __STILTS_COLOR_GREEN   ""
#define __STILTS_COLOR_YELLOW  ""
#define __STILTS_COLOR_BLUE    ""
#define __STILTS_COLOR_MAGENTA ""
#define __STILTS_COLOR_CYAN    ""
#define __STILTS_COLOR_RESET   ""
#endif /* __STILTS_ANSI_TERMINAL */

#define __STILTS_COLOR_HEAD(str) __STILTS_COLOR_RED str __STILTS_COLOR_RESET
#define __STILTS_COLOR_PNIC(str) __STILTS_COLOR_RED str __STILTS_COLOR_RESET
#define __STILTS_COLOR_PNTR(str) __STILTS_COLOR_MAGENTA str __STILTS_COLOR_RESET
#define __STILTS_COLOR_BYTE(str) __STILTS_COLOR_BLUE str __STILTS_COLOR_RESET
#define __STILTS_COLOR_FILE(str) __STILTS_COLOR_GREEN str __STILTS_COLOR_RESET
#define __STILTS_COLOR_FUNC(str) __STILTS_COLOR_YELLOW str __STILTS_COLOR_RESET
#define __STILTS_COLOR_LINE(str) __STILTS_COLOR_CYAN str __STILTS_COLOR_RESET

#endif /* __STILTS_STDLIB_COLOR */
