// THIS FILE GENERATED BY GenNodeTypes.py. DO NOT EDIT.
#ifndef INCLUDE_ASTNODETYPE
#define INCLUDE_ASTNODETYPE
#include <apaz-libc.h>

enum ASTNodeType {
  CompilationUnit,
  TopLevelDecl,
  EnumDecl,
  TraitDecl,
  ClassDecl,
  FunctionDecl,
  CTypeDecl,
  GlobalVarDecl,
};
typedef enum ASTNodeType ASTNodeType;
#endif // INCLUDE_ASTNODETYPE